name: MacOs

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Download staticlib
        run: curl -L https://github.com/anshulrgoyal/imageflow/releases/download/v1.4.0-rc40/libimageflow_mac.zip > libimageflow.a
      - name: Download Image
        run: curl -L https://jpeg.org/images/jpeg2000-home.jpg > image.jpg
      - name: Test
        run: go test -ldflags=\"-extldflags=-static\" -v
